export interface Player {
    id: string
    name: string
    SEASON_ID: string
    LEAGUE_ID: string
    TEAM_ID: string
    TEAM_ABBREVIATION: string
    PLAYER_AGE: number
    GP: number
    GS: number
    MIN: number
    FGM: number
    FGA: number
    FG_PCT: number
    FG3M: number
    FG3A: number
    FG3_PCT: number
    FTM: number
    FTA: number
    FT_PCT: number
    OREB: number
    DREB: number
    REB: number
    AST: number
    STL: number
    BLK: number
    TOV: number
    PF: number
    PTS: number
}